project:
  type: website
  output-dir: docs

website:
  title: "Ryan Stephenson, CNUa"
  favicon: naturesprez.github.io\img\apple-touch-icon-57x57.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Plans.qmd
        text: Plans
      - href: cv/RyanStephenson_CV_11012022.pdf
      - text: CV

format:
  html:
    theme: sketchy
    css: bootstrap.css
    toc: true



