project:
  type: website
  output-dir: docs

website:
  title: "Ryan Stephenson, CNUa"
<<<<<<< HEAD
  favicon: naturesprez.github.io\img\favicon.ico
=======
  favicon: naturesprez.github.io\imgimg\favicon
>>>>>>> d1762afc02034c6c0fc6b62b46a52801003502bc
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Plans.qmd
        text: Plans
      - href: cv/RyanStephenson_CV_11012022.pdf
      - text: CV

format:
  html:
    theme: sketchy
    css: bootstrap.css
    toc: true



