project:
  type: website
  output-dir: docs

website:
  title: "Ryan Stephenson, CNUa"
  favicon: img/apple-touch-icon-57x57.png # idk why this reqs a /
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Plans.qmd
        text: Plans
      - href: cv\RyanStephenson_CV_11012022.pdf # but this reqs a \
        text: CV

format:
  html:
    theme: sketchy
    css: bootstrap.css
    toc: true



